/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#feae2c",
        "surface-dim": "#d7dadd",
        "on-tertiary": "#ffffff",
        outline: "#75777e",
        "on-surface": "#181c1e",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#091b38",
        "inverse-on-surface": "#eef1f4",
        "tertiary-fixed": "#d4e3ff",
        secondary: "#835500",
        "on-secondary-fixed-variant": "#633f00",
        "surface-container-low": "#f1f4f7",
        "error-container": "#ffdad6",
        tertiary: "#00040d",
        "surface-container-lowest": "#ffffff",
        surface: "#f7fafd",
        "surface-tint": "#4f5e7f",
        "on-secondary-container": "#6b4500",
        "on-tertiary-fixed-variant": "#374860",
        error: "#ba1a1a",
        "secondary-fixed": "#ffddb4",
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#374766",
        "surface-bright": "#f7fafd",
        "surface-container-highest": "#e0e3e6",
        "tertiary-container": "#0c1e34",
        "on-error-container": "#93000a",
        "primary-fixed": "#d7e2ff",
        "surface-container": "#ebeef1",
        "primary-container": "#0b1d3a",
        background: "#f7fafd",
        "inverse-primary": "#b6c7ec",
        "primary-fixed-dim": "#b6c7ec",
        "on-surface-variant": "#44474d",
        "on-error": "#ffffff",
        "on-background": "#181c1e",
        "on-secondary-fixed": "#291800",
        "on-tertiary-fixed": "#0a1c32",
        "on-tertiary-container": "#7686a1",
        "secondary-fixed-dim": "#ffb955",
        "surface-container-high": "#e5e8eb",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c6ce",
        "tertiary-fixed-dim": "#b6c7e5",
        primary: "#00030f",
        "surface-variant": "#e0e3e6",
        "on-primary-container": "#7585a8",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: { lg: "24px", unit: "4px", md: "16px", "container-margin": "20px", gutter: "16px", xl: "48px", sm: "8px", xs: "4px" },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};